openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /post:
    post:
      description: "Create a new post"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostDTO"
      responses:
        "201":
          description: "Post Created"
        "500":
          description: "Internal Server Error"

    get:
      description: "Get all posts"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PostDTO"
        "500":
          description: "Internal Server Error"

  /post/{postId}:
    get:
      description: "Get a post by postId"
      parameters:
        - name: "postId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostDTO"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Error"

    put:
      description: "Update a post by postId"
      parameters:
        - name: "postId"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostDTO"
      responses:
        "200":
          description: "Update Successful"
        "409":
          description: "Conflict"
        "500":
          description: "Internal Server Error"

    delete:
      description: "Delete a post by postId"
      parameters:
        - name: "postId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Deleted Successfully"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Error"

components:
  schemas:
    PostDTO:
      type: object
      properties:
        postId:
          type: string
        whomPosted:
          type: string
        postMessage:
          type: string
        whenPosted:
          type: string
